# Part 1

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


1. Load the wine dataset from the given ‘wine.csv’ file into a variable (say data). 
2. From the variable, extract the numerical information into a new variable, say scores. 


In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
import statistics

##### question 1 ########
df= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/wine.csv',sep=',',header=None)
data =df.values
print(data)

###### question 2 ######
score1 = np.array(data)
#print(score1)

score = np.delete(score1,(0),axis=0)
score = score.astype(np.float)

print("\n")
# print("after removing from the first row from the matrix")
print(score)
print("\n")





[['Wine' 'Alcohol' 'Malic.acid' ... 'Hue' 'OD' 'Proline']
 ['1' '14.23' '1.71' ... '1.04' '3.92' '1065']
 ['1' '13.2' '1.78' ... '1.05' '3.4' '1050']
 ...
 ['3' '13.27' '4.28' ... '.59' '1.56' '835']
 ['3' '13.17' '2.59' ... '.6' '1.62' '840']
 ['3' '14.13' '4.1' ... '.61' '1.6' '560']]
[['Wine' 'Alcohol' 'Malic.acid' ... 'Hue' 'OD' 'Proline']
 ['1' '14.23' '1.71' ... '1.04' '3.92' '1065']
 ['1' '13.2' '1.78' ... '1.05' '3.4' '1050']
 ...
 ['3' '13.27' '4.28' ... '.59' '1.56' '835']
 ['3' '13.17' '2.59' ... '.6' '1.62' '840']
 ['3' '14.13' '4.1' ... '.61' '1.6' '560']]


after removing from the first row from the matrix
[[1.000e+00 1.423e+01 1.710e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.000e+00 1.320e+01 1.780e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.000e+00 1.316e+01 2.360e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [3.000e+00 1.327e+01 4.280e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [3.000e+00 1.317e+01 2.590e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [3.000e+00 1.413e+01 4.100e+00 

3. Calculate the row-wise,column-wise, and overall mean, median, mode, and standard deviation of the dataset. In this question write separate functions for each operation and pass the variable(scores) as the parameter to the function. 


In [ ]:
# finding mean, median,mode and standard deviation row-wise and column wise and overall .
import numpy as np
from scipy import stats

# overall mean
print("mean of matrix \n",np.mean(score))
print("\n")

# overall median 
print("median of matrix \n",np.median(score))
print("\n")

# overall mode of the .csv numeriacal value
print("overall mode \n",stats.mode(score))
print("\n")

# overall standard deviation
print("overall standard deviation is \n",np.std(score))

# row wise operation
print("mean of matrix row wise\n",score.mean(axis=1))
print()
print("median of matrix row-wise \n",np.median(score,axis=1))
print()
print("mode of matrix row-wise\n")
print(stats.mode(score,axis=1))


#column wise
print("mean of matrix column wise\n",score.mean(axis=0))
print()
print("median of matrix column-wise \n",np.median(score,axis=0))
print()
print("mode of matrix column-wise\n")
print(stats.mode(score,axis=0))
print("\n")

mean of matrix 
 64.33398715850723


median of matrix 
 2.6


overall mode 
 ModeResult(mode=array([[2.000e+00, 1.237e+01, 1.730e+00, 2.280e+00, 2.000e+01, 8.800e+01,
        2.200e+00, 2.650e+00, 2.600e-01, 1.350e+00, 2.600e+00, 1.040e+00,
        2.870e+00, 5.200e+02]]), count=array([[71,  6,  7,  7, 15, 13,  8,  4, 11,  9,  4,  8,  5,  5]]))


overall standard deviation is 
 208.61735837075227
mean of matrix row wise
 [ 89.          85.36428571  95.91571429 117.96357143  64.97785714
 115.445      102.67571429 104.98428571  85.20142857  85.53285714
 119.4        101.86928571 104.35714286  92.26285714 121.60857143
 105.52285714 104.15        93.05642857 131.85142857  72.39142857
  68.56642857  66.22        84.84928571  82.92785714  71.10428571
  72.42357143  95.67142857 102.00785714  77.01214286  84.46142857
 103.28214286 119.84214286  81.82214286 101.62        89.84571429
  76.90071429  74.265       89.55285714  83.245       67.19714286
  69.02571429  84.23142857  89.20785714  59.745

# Part 2

1. Take the ‘alcohol’ and ‘Proline’ as the features from the ‘wine.csv’ dataset and calculate the pearson correlation for the same. 

In [ ]:
from scipy.stats import pearsonr



x,y = score[:,1],score[:,13]
print("pearson co-relation for wine and and alcohal \n")
corr,_ = pearsonr(x,y)
print('Pearsons correlation: %.3f' % corr)



pearson co-relation for wine and and alcohal 

Pearsons correlation: 0.644


2. Take any 5 features from the ‘wine.csv’ datasets and load them in a matrix. Thereafter, create the covariance matrix of the 

In [ ]:
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
ds= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/wine.csv',sep=',',header=0)
matrix = ds[["Ash","Acl","Mg","Phenols","Flavanoids"]]
cov_mat = matrix.cov()
print(cov_mat)
#sn.heatmap(cov_mat, annot=True)
#plt.show()

                 Ash        Acl          Mg   Phenols  Flavanoids
Ash         0.075265   0.406208    1.122937  0.022146    0.031535
Acl         0.406208  11.152686   -3.974760 -0.671149   -1.172083
Mg          1.122937  -3.974760  203.989335  1.916470    2.793087
Phenols     0.022146  -0.671149    1.916470  0.391690    0.540470
Flavanoids  0.031535  -1.172083    2.793087  0.540470    0.997719
